"use client";

import { useEffect, useState } from "react";

type Show = { id: string; fechaHora: string; cupoTotal: number; pelicula: { titulo: string } };
type Booking = { id: string; nombre: string; contacto: string; cantidad: number; createdAt: string };
export default function AdminReservationsPage() {
  const [shows, setShows] = useState<Show[]>([]); const [selected, setSelected] = useState(""); const [bookings, setBookings] = useState<Booking[] | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch("/api/funciones").then(async (res) => { if (!res.ok) throw new Error("No se pudieron cargar las funciones"); const data = await res.json(); setShows(data.funciones || []); setSelected(data.funciones?.[0]?.id || ""); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!selected) { setBookings([]); return; } setBookings(null); fetch(`/api/admin/funciones/${selected}/reservas`, { credentials: "include" }).then(async (res) => { if (!res.ok) throw new Error("No se pudieron cargar las reservas"); setBookings((await res.json()).reservas || []); }).catch((e) => setError(e.message)); }, [selected]);
  if (loading) return <div className="h-64 animate-pulse rounded-xl bg-white/5" />;
  const show = shows.find((item) => item.id === selected);
  return <div className="space-y-6"><div><h2 className="text-2xl font-bold">Reservas</h2><p className="mt-1 text-sm text-white/60">Consulta las reservas por función.</p></div>{error && <div role="alert" className="rounded-lg bg-red-500/10 px-4 py-3 text-sm text-red-300">{error}</div>}{!shows.length && !error && <div className="surface-card p-8 text-center text-sm text-white/60">No hay funciones disponibles.</div>}{shows.length > 0 && <><div className="surface-card p-5"><label htmlFor="reservation-show" className="text-xs text-white/60">Función</label><select id="reservation-show" value={selected} onChange={(e) => setSelected(e.target.value)} className="control-dark mt-1 w-full px-3 py-2 text-sm">{shows.map((item) => <option key={item.id} value={item.id}>{item.pelicula.titulo} · {new Date(item.fechaHora).toLocaleString("es-CO", { dateStyle: "medium", timeStyle: "short" })}</option>)}</select></div>{bookings === null && <div className="h-48 animate-pulse rounded-xl bg-white/5" />}{bookings && <section className="surface-card overflow-x-auto p-5"><div className="mb-4"><h3 className="font-bold">{show?.pelicula.titulo}</h3><p className="text-sm text-white/50">{bookings.length} reservas registradas</p></div>{bookings.length === 0 ? <p className="py-6 text-center text-sm text-white/50">Aún no hay reservas para esta función.</p> : <table className="w-full min-w-[600px] text-sm"><thead><tr className="border-b border-white/10 text-left text-xs text-white/50"><th className="pb-3">Cliente</th><th className="pb-3">Contacto</th><th className="pb-3">Personas</th><th className="pb-3">Creada</th></tr></thead><tbody>{bookings.map((booking) => <tr key={booking.id} className="border-b border-white/5"><td className="py-3">{booking.nombre}</td><td className="py-3 text-white/70">{booking.contacto}</td><td className="py-3 text-white/70">{booking.cantidad}</td><td className="py-3 text-white/50">{new Date(booking.createdAt).toLocaleString("es-CO", { dateStyle: "short", timeStyle: "short" })}</td></tr>)}</tbody></table>}</section>}</>}</div>;
}
